version: '3.8'

services:
  app:
    build: .
    container_name: uas-static-app
    restart: always
    ports:
      - "3000:80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
