version: '3.8'

services:
  # 1. Aplikasi Web Utama (Static App)
  web-app:
    image: nginx:alpine
    container_name: uas-static-app
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html

  # 2. Nginx Reverse Proxy (HTTPS & Gateway)
  reverse-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web-app

  # 3. Certbot SSL Auto-Renewal
  certbot:
    image: certbot/certbot
    container_name: certbot-ssl
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # 4. Uptime Kuma Monitoring Dashboard (Akses via Port 3001)
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data

volumes:
  certbot-etc:
  certbot-var:
  uptime-kuma-data: