events { worker_connections 1024; }

http {
    # 1. Alur Otomatis: Paksa HTTP (Port 80) Pindah ke HTTPS (Port 443)
    server {
        listen 80;
        server_name psbfajrussalam.my.id www.psbfajrussalam.my.id;

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # 2. Alur Utama HTTPS (Port 443) dengan Keamanan SSL
    server {
        listen 443 ssl;
        server_name psbfajrussalam.my.id www.psbfajrussalam.my.id;

        ssl_certificate /etc/letsencrypt/live/psbfajrussalam.my.id/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/psbfajrussalam.my.id/privkey.pem;

        location / {
            proxy_pass http://web-app:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}