name: Proyek Akhir DevOps CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Menjalankan Perintah Deployment di VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: '202.10.36.46'
          username: 'root'
          password: '4We7p#2f0aF%8H' 
          script: |
            cd ~/Praktikum-devops-tazkia

            # Paksa hapus perubahan lokal VPS dan tarik commit terbaru dari GitHub
            git fetch --all
            git reset --hard origin/main

            # Bongkar kontainer lama dan bangun ulang secara bersih tanpa cache
            docker compose down
            docker compose up -d --build
